# Generated by Django 3.2.4 on 2021-07-06 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_billinginfo_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='grupo',
            field=models.CharField(choices=[('A', 'Grupo A'), ('B', 'Grupo B')], max_length=1),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='modalidade_tarifaria',
            field=models.CharField(choices=[('Azul', 'Azul'), ('Branca', 'Branca'), ('Verde', 'Verde')], max_length=6),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='sub_grupo',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A3a', 'A3a'), ('A4', 'A4'), ('AS', 'AS'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4')], max_length=3),
        ),
    ]
