# Generated by Django 3.2.4 on 2021-07-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210706_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='modalidade_tarifaria',
            field=models.CharField(choices=[('Convencional', 'Convencional'), ('Azul', 'Azul'), ('Branca', 'Branca'), ('Verde', 'Verde')], max_length=12),
        ),
    ]
