# Generated by Django 3.2.4 on 2021-07-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_billinginfo_modalidade_tarifaria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
