# Generated by Django 3.2.4 on 2021-07-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_kwhtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwhtotal',
            name='kwh_sum',
            field=models.FloatField(default=0.0),
        ),
    ]
