# Generated by Django 3.2.4 on 2021-07-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_kwhtotal_kwh_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_by_Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_name', models.CharField(max_length=32)),
                ('kwh_sum', models.FloatField()),
            ],
        ),
    ]
