# Generated by Django 3.2.4 on 2021-08-07 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_alter_tax_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloadassociation',
            name='load',
        ),
        migrations.AddField(
            model_name='userloadassociation',
            name='load',
            field=models.ManyToManyField(to='api.Load'),
        ),
        migrations.RemoveField(
            model_name='userloadassociation',
            name='user',
        ),
        migrations.AddField(
            model_name='userloadassociation',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
