# Generated by Django 3.2.4 on 2021-08-07 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_auto_20210807_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloadassociation',
            name='load',
        ),
        migrations.AddField(
            model_name='userloadassociation',
            name='Load',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.load'),
        ),
        migrations.RemoveField(
            model_name='userloadassociation',
            name='user',
        ),
        migrations.AddField(
            model_name='userloadassociation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
