# Generated by Django 3.2.4 on 2021-08-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210807_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloadassociation',
            name='Load',
        ),
        migrations.AddField(
            model_name='userloadassociation',
            name='load',
            field=models.ManyToManyField(to='api.Load'),
        ),
    ]
