# Generated by Django 3.2.4 on 2021-08-15 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_userloadassociation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='trackedLoads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isTracked', models.BooleanField()),
                ('load', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.load')),
            ],
        ),
    ]
