# Generated by Django 3.2.4 on 2021-08-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_trackedloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedloads',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.load'),
        ),
    ]
